import os
from typing import Optional

from .parser import ParserFactory
from .analyzer import CodeAnalyzer
from .standardization import StandardizationCalculator, DefaultStandardizationCalculator
from .models import DiffResult

class AnalyzerEngine:
    """
    High-level facade for the AST-based diff engine.
    Orchestrates the parsing of files and the diffing process.
    """
    
    def __init__(self, stn_calculator: Optional[StandardizationCalculator] = None, use_ast_diff: bool = False, excludes: list = None):
        self.analyzer = CodeAnalyzer()
        self.stn_calculator = stn_calculator or DefaultStandardizationCalculator()
        self.use_ast_diff = use_ast_diff
        self.excludes = excludes or []
        
    def compare_files(self, old_file_path: str, new_file_path: str, ignore_formatting: bool = False) -> dict:
        """
        Compare two files and return a comprehensive analysis dictionary.
        """
        if not os.path.exists(old_file_path):
            raise FileNotFoundError(f"Old file not found: {old_file_path}")
        if not os.path.exists(new_file_path):
            raise FileNotFoundError(f"New file not found: {new_file_path}")
            
        # 1. Parse both files
        old_parser = ParserFactory.get_parser(old_file_path)
        new_parser = ParserFactory.get_parser(new_file_path)
        
        old_funcs = old_parser.parse_file(old_file_path)
        new_funcs = new_parser.parse_file(new_file_path)
        
        # 2. Analyze differences
        if self.use_ast_diff:
            from .ast_diff import ASTDiffer
            ast_analyzer = ASTDiffer()
            diff_result = ast_analyzer.analyze_functions_ast(old_funcs, new_funcs)
        else:
            diff_result = self.analyzer.analyze_functions(old_funcs, new_funcs, ignore_formatting=ignore_formatting)
        
        # 3. Calculate standardization rate using the extension interface
        std_rate = self.stn_calculator.calculate(diff_result)
        
        # 4. Format report
        report = {
            "target": new_file_path,
            "type": "file",
            "metrics": {
                "added_functions": diff_result.added_functions,
                "deleted_functions": diff_result.deleted_functions,
                "modified_functions": diff_result.modified_functions,
                "lines_added_in_mod": diff_result.lines_added,
                "lines_deleted_in_mod": diff_result.lines_deleted
            },
            "design_standardization_rate": std_rate,
            "details": {
                "added": [{"name": f.name, "file": f.file_path} for f in diff_result.added_func_details],
                "deleted": [{"name": f.name, "file": f.file_path} for f in diff_result.deleted_func_details],
                "modified": [
                    {
                        "name": new_node.name,
                        "file": new_node.file_path,
                        "lines_added": added,
                        "lines_deleted": deleted,
                        "ast_nodes_modified": ast_mod[0] if ast_mod else 0,
                        "ast_change_details": ast_mod[4] if len(ast_mod) >= 5 else [],
                        "old_content": old_node.content,
                        "new_content": new_node.content
                    }
                    for old_node, new_node, added, deleted, *ast_mod in diff_result.modified_func_details
                ]
            }
        }
        
        if self.use_ast_diff:
            report["ast_metrics"] = {
                "ast_nodes_added": diff_result.ast_nodes_added,
                "ast_nodes_deleted": diff_result.ast_nodes_deleted,
                "ast_nodes_modified": diff_result.ast_nodes_modified,
                "ast_lines_added": diff_result.ast_lines_added,
                "ast_lines_deleted": diff_result.ast_lines_deleted,
                "ast_lines_modified": diff_result.ast_lines_modified
            }
        
        return report
        
    def _is_qt_generated_file(self, file_path: str) -> bool:
        """Check if the file is auto-generated by Qt tools."""
        basename = os.path.basename(file_path).lower()
        if basename.startswith('moc_') and basename.endswith('.cpp'):
            return True
        if basename.startswith('ui_') and basename.endswith('.h'):
            return True
        if basename.startswith('qrc_') and basename.endswith('.cpp'):
            return True
        if basename.endswith('.moc'):
            return True
        return False
        
    def _is_excluded(self, file_path: str) -> bool:
        """Check if any part of the path strictly matches an exclude rule."""
        if not self.excludes:
            return False
            
        # Get all parts of the path
        parts = []
        head, tail = os.path.split(file_path)
        while tail:
            parts.append(tail)
            head, tail = os.path.split(head)
        if head:
            parts.append(head)
            
        return any(excl in parts for excl in self.excludes)

    def _is_supported_file(self, file_path: str) -> bool:
        if self._is_qt_generated_file(file_path):
            return False
            
        if self._is_excluded(file_path):
            return False
            
        ext = os.path.splitext(file_path)[1].lower()
        # return ext in ('.c', '.h', '.cpp', '.cxx', '.cc', '.hpp', '.hxx', '.xml')
        return ext in ('.c', '.h', '.cpp', '.cxx', '.cc', '.hpp', '.hxx')

    def _collect_functions_from_dir(self, directory: str) -> list:
        funcs = []
        for root, _, files in os.walk(directory):
            for file in files:
                file_path = os.path.join(root, file)
                if self._is_supported_file(file_path):
                    try:
                        parser = ParserFactory.get_parser(file_path)
                        funcs.extend(parser.parse_file(file_path))
                    except Exception as e:
                        print(f"Warning: Failed to parse {file_path}: {e}")
        return funcs

    def _collect_relative_files(self, directory: str) -> set:
        """Collect relative paths of all supported source files in a directory."""
        files = set()
        for root, _, filenames in os.walk(directory):
            for f in filenames:
                full = os.path.join(root, f)
                if self._is_supported_file(full):
                    files.add(os.path.relpath(full, directory))
        return files

    def compare_directories(self, old_dir_path: str, new_dir_path: str, ignore_formatting: bool = False) -> dict:
        if not os.path.exists(old_dir_path):
            raise FileNotFoundError(f"Old directory not found: {old_dir_path}")
        if not os.path.exists(new_dir_path):
            raise FileNotFoundError(f"New directory not found: {new_dir_path}")

        # 0. Detect file-level additions / deletions
        old_files = self._collect_relative_files(old_dir_path)
        new_files = self._collect_relative_files(new_dir_path)
        added_files = sorted(new_files - old_files)
        deleted_files = sorted(old_files - new_files)

        # 1. Parse all functions
        old_funcs = self._collect_functions_from_dir(old_dir_path)
        new_funcs = self._collect_functions_from_dir(new_dir_path)

        # 2. Analyze
        if self.use_ast_diff:
            from .ast_diff import ASTDiffer
            ast_analyzer = ASTDiffer()
            diff_result = ast_analyzer.analyze_functions_ast(old_funcs, new_funcs)
        else:
            diff_result = self.analyzer.analyze_functions(old_funcs, new_funcs, ignore_formatting=ignore_formatting)

        std_rate = self.stn_calculator.calculate(diff_result)

        def _rel(path):
            """Convert absolute path to directory-relative path for cleaner display."""
            try:
                return os.path.relpath(path, new_dir_path)
            except ValueError:
                return path

        report = {
            "target": new_dir_path,
            "type": "directory",
            "metrics": {
                "added_functions": diff_result.added_functions,
                "deleted_functions": diff_result.deleted_functions,
                "modified_functions": diff_result.modified_functions,
                "lines_added_in_mod": diff_result.lines_added,
                "lines_deleted_in_mod": diff_result.lines_deleted
            },
            "design_standardization_rate": std_rate,
            "details": {
                "added": [{"name": f.name, "file": _rel(f.file_path)} for f in diff_result.added_func_details],
                "deleted": [{"name": f.name, "file": _rel(f.file_path)} for f in diff_result.deleted_func_details],
                "modified": [
                    {
                        "name": new_node.name,
                        "file": _rel(new_node.file_path),
                        "lines_added": added,
                        "lines_deleted": deleted,
                        "ast_nodes_modified": ast_mod[0] if ast_mod else 0,
                        "ast_change_details": ast_mod[4] if len(ast_mod) >= 5 else [],
                        "old_content": old_node.content,
                        "new_content": new_node.content
                    }
                    for old_node, new_node, added, deleted, *ast_mod in diff_result.modified_func_details
                ]
            }
        }
        
        if self.use_ast_diff:
            report["ast_metrics"] = {
                "ast_nodes_added": diff_result.ast_nodes_added,
                "ast_nodes_deleted": diff_result.ast_nodes_deleted,
                "ast_nodes_modified": diff_result.ast_nodes_modified,
                "ast_lines_added": diff_result.ast_lines_added,
                "ast_lines_deleted": diff_result.ast_lines_deleted,
                "ast_lines_modified": diff_result.ast_lines_modified
            }

        report["file_changes"] = {
            "added_files": added_files,
            "deleted_files": deleted_files
        }

        return report
