from abc import ABC, abstractmethod
from .models import DiffResult

class StandardizationCalculator(ABC):
    """
    Abstract interface for calculating the Design Standardization Rate.
    Provide your own implementation by subclassing this and overriding `calculate`.
    """
    
    @abstractmethod
    def calculate(self, diff_result: DiffResult) -> float:
        """
        Calculate and return the standardization rate based on the diff result.
        
        :param diff_result: The raw DiffResult generated by the analyzer.
        :return: A float value representing the standardization rate (e.g., 0.0 ~ 1.0 or percentage)
        """
        pass

class DefaultStandardizationCalculator(StandardizationCalculator):
    """
    A default, dummy implementation of StandardizationCalculator.
    """
    def calculate(self, diff_result: DiffResult) -> float:
        # Default behavior: not implemented, returns 0.0 or a basic generic metric.
        # User should override this to provide specific logic.
        total_functions = diff_result.added_functions + diff_result.modified_functions
        if total_functions == 0:
            return 1.0
        
        # Just an example generic formula
        # Return 0 to indicate it requires user-defined logic
        return 0.0
